version: '2'
services:
  # for development purposes
  dev:
    build: .
    image: "pocin/kbc-processor-decompress-lzo:dev"
    volumes:
        - ./:/code
        - ./data/out/files/:/data/out/files/
    command:
      - /bin/sh
